TRADUCCIONES = {
    'es': {
        'dashboard': 'Dashboard',
        'cuentas': 'Cuentas',
        'transacciones': 'Transacciones',
        'reportes': 'Reportes',
        'presupuestos': 'Presupuestos',
        'asistente': 'Asistente',
        'perfil': 'Perfil',
        'salir': 'Salir',
        'modo_oscuro': 'Modo Oscuro',
        'modo_claro': 'Modo Claro',
        'bienvenido': 'Bienvenido',
        'total_ingresos': 'Total Ingresos',
        'total_gastos': 'Total Gastos',
        'balance_total': 'Balance Total',
        'ultimas_transacciones': 'Últimas Transacciones',
        'ver_todas': 'Ver todas',
        'nueva_transaccion': 'Nueva Transacción',
        'editar': 'Editar',
        'eliminar': 'Eliminar',
        'confirmar_eliminacion': 'Confirmar Eliminación',
        'mensaje_confirmar_eliminacion': '¿Estás seguro de que deseas eliminar este elemento? Esta acción no se puede deshacer.',
        'cancelar': 'Cancelar',
        'guardar': 'Guardar',
        'crear': 'Crear',
        'idioma': 'Idioma',
        'espanol': 'Español',
        'ingles': 'Inglés',
        'nombre': 'Nombre',
        'tipo': 'Tipo',
        'monto': 'Monto',
        'fecha': 'Fecha',
        'descripcion': 'Descripción',
        'categoria': 'Categoría',
        'cuenta': 'Cuenta',
        'saldo_inicial': 'Saldo Inicial',
        'divisa': 'Divisa',
        'periodo': 'Periodo',
        'fecha_inicio': 'Fecha Inicio',
        'fecha_fin': 'Fecha Fin',
        'alertas_presupuesto': 'Alertas de Presupuesto',
        'ingresos': 'Ingresos',
        'gastos': 'Gastos',
        'balance': 'Balance',
        'enviar_por_email': 'Enviar por Email',
        'exportar_csv': 'Exportar CSV',
        'mis_cuentas': 'Mis Cuentas',
        'nueva_cuenta': 'Nueva Cuenta',
        'nuevo_presupuesto': 'Nuevo Presupuesto',
        'cambiar_contrasena': 'Cambiar Contraseña',
        'contrasena_actual': 'Contraseña Actual',
        'contrasena_nueva': 'Nueva Contraseña',
        'confirmar_contrasena': 'Confirmar Contraseña',
        'actualizar': 'Actualizar',
        'registro_rapido': 'Registro Rápido de Transacción',
        'gasto': 'Gasto',
        'ingreso': 'Ingreso',
        'no_alertas': 'No hay alertas activas.',
        'mensaje_alerta': 'Has consumido el {porcentaje}% del presupuesto para {categoria} ({actual} de {limite}).',
        'saldo': 'Saldo',
        'saldo_actual': 'Saldo Actual',
        'registro_rapido_desc': 'Registro rápido',
        'login': 'Iniciar Sesión',
        'email': 'Email',
        'contrasena': 'Contraseña',
        'no_tienes_cuenta': '¿No tienes cuenta?',
        'registrate': 'Regístrate',
        'ya_tienes_cuenta': '¿Ya tienes cuenta?',
        'nombre_completo': 'Nombre Completo',
        'registrar': 'Registrar',
        'no_cuentas': 'No tienes cuentas registradas todavía.',
        'nombre_cuenta': 'Nombre de la Cuenta',
        'mis_cuentas_registradas': 'Mis Cuentas Registradas',
        'crear_cuenta': 'Crear Cuenta',
        'limite': 'Límite',
        'filtros_avanzados': 'Filtros Avanzados',
        'desde': 'Desde',
        'hasta': 'Hasta',
        'filtrar_fecha': 'Filtrar por Fecha',
        'historial': 'Historial',
        'buscar_placeholder': 'Buscar categoría, desc...',
        'reportes_financieros': 'Reportes Financieros',
        'ingresos_vs_gastos_6': 'Ingresos vs Gastos (Últimos 6 Meses)',
        'gastos_cat_mes': 'Gastos por Categoría (Mes Actual)',
        'balance_mensual': 'Balance Mensual',
        'monto_total': 'Monto Total',
        'top_gastos_hist': 'Top 5 Gastos Históricos',
        'total_may': 'Total',
        'enviar_reporte_email': 'Enviar reporte por email',
        'configurar_presupuesto': 'Configurar Presupuesto',
        'limite_monto': 'Límite de Monto',
        'limites_establecidos': 'Límites Establecidos',
        'vence': 'Vence',
        'mensual': 'Mensual',
        'anual': 'Anual',
        'crear_presupuesto': 'Crear Presupuesto',
        'registrarse': 'Registrarse',
        'entrar': 'Entrar',
        'mi_perfil': 'Mi Perfil',
        'fecha_registro': 'Fecha de registro',
        'guardar_cambios': 'Guardar Cambios',
        'asistente_financiero': 'Asistente Financiero',
        'hola_asistente': 'Hola, {nombre}. Soy tu asistente financiero.',
        'analisis_asistente': 'He analizado tus cuentas, gastos y presupuestos. ¿En qué puedo ayudarte hoy?',
        'pregunta_placeholder': 'Pregúntame sobre tus gastos, ahorros o presupuestos...',
        'enviar': 'Enviar',
        'info_asistente': 'El asistente tiene acceso a tu balance mensual, top gastos y presupuestos actuales para darte consejos personalizados.',
        'acciones': 'Acciones',
        'divisas': 'Divisas',
        'convertidor_divisas': 'Convertidor de Divisas',
        'monto_a_convertir': 'Monto a convertir',
        'divisa_origen': 'Divisa Origen',
        'divisa_destino': 'Divisa Destino',
        'convertir': 'Convertir',
        'resultado_conversion': 'Resultado de la Conversión',
        'error_conversion': 'Error al obtener la tasa de cambio.',
    },
    'en': {
        'dashboard': 'Dashboard',
        'cuentas': 'Accounts',
        'transacciones': 'Transactions',
        'reportes': 'Reports',
        'presupuestos': 'Budgets',
        'asistente': 'Assistant',
        'perfil': 'Profile',
        'salir': 'Logout',
        'modo_oscuro': 'Dark Mode',
        'modo_claro': 'Light Mode',
        'bienvenido': 'Welcome',
        'total_ingresos': 'Total Income',
        'total_gastos': 'Total Expenses',
        'balance_total': 'Total Balance',
        'ultimas_transacciones': 'Last Transactions',
        'ver_todas': 'View all',
        'nueva_transaccion': 'New Transaction',
        'editar': 'Edit',
        'eliminar': 'Delete',
        'confirmar_eliminacion': 'Confirm Deletion',
        'mensaje_confirmar_eliminacion': 'Are you sure you want to delete this item? This action cannot be undone.',
        'cancelar': 'Cancel',
        'guardar': 'Save',
        'crear': 'Create',
        'idioma': 'Language',
        'espanol': 'Spanish',
        'ingles': 'English',
        'nombre': 'Name',
        'tipo': 'Type',
        'monto': 'Amount',
        'fecha': 'Date',
        'descripcion': 'Description',
        'categoria': 'Category',
        'cuenta': 'Account',
        'saldo_inicial': 'Initial Balance',
        'divisa': 'Currency',
        'periodo': 'Period',
        'fecha_inicio': 'Start Date',
        'fecha_fin': 'End Date',
        'alertas_presupuesto': 'Budget Alerts',
        'ingresos': 'Income',
        'gastos': 'Expenses',
        'balance': 'Balance',
        'enviar_por_email': 'Send by Email',
        'exportar_csv': 'Export CSV',
        'mis_cuentas': 'My Accounts',
        'nueva_cuenta': 'New Account',
        'nuevo_presupuesto': 'New Budget',
        'cambiar_contrasena': 'Change Password',
        'contrasena_actual': 'Current Password',
        'contrasena_nueva': 'New Password',
        'confirmar_contrasena': 'Confirm Password',
        'actualizar': 'Update',
        'registro_rapido': 'Quick Transaction Record',
        'gasto': 'Expense',
        'ingreso': 'Income',
        'no_alertas': 'No active alerts.',
        'mensaje_alerta': 'You have consumed {porcentaje}% of the budget for {categoria} ({actual} of {limite}).',
        'saldo': 'Balance',
        'saldo_actual': 'Current Balance',
        'registro_rapido_desc': 'Quick record',
        'login': 'Login',
        'email': 'Email',
        'contrasena': 'Password',
        'no_tienes_cuenta': "Don't have an account?",
        'registrate': 'Sign up',
        'ya_tienes_cuenta': 'Already have an account?',
        'nombre_completo': 'Full Name',
        'registrar': 'Register',
        'no_cuentas': 'You have no registered accounts yet.',
        'nombre_cuenta': 'Account Name',
        'mis_cuentas_registradas': 'My Registered Accounts',
        'crear_cuenta': 'Create Account',
        'limite': 'Limit',
        'filtros_avanzados': 'Advanced Filters',
        'desde': 'From',
        'hasta': 'To',
        'filtrar_fecha': 'Filter by Date',
        'historial': 'History',
        'buscar_placeholder': 'Search category, desc...',
        'reportes_financieros': 'Financial Reports',
        'ingresos_vs_gastos_6': 'Income vs Expenses (Last 6 Months)',
        'gastos_cat_mes': 'Expenses by Category (Current Month)',
        'balance_mensual': 'Monthly Balance',
        'monto_total': 'Total Amount',
        'top_gastos_hist': 'Top 5 Historical Expenses',
        'total_may': 'Total',
        'enviar_reporte_email': 'Send report by email',
        'configurar_presupuesto': 'Set Budget',
        'limite_monto': 'Amount Limit',
        'limites_establecidos': 'Established Limits',
        'vence': 'Expires',
        'mensual': 'Monthly',
        'anual': 'Annual',
        'crear_presupuesto': 'Create Budget',
        'registrarse': 'Register',
        'entrar': 'Login',
        'mi_perfil': 'My Profile',
        'fecha_registro': 'Registration date',
        'guardar_cambios': 'Save Changes',
        'asistente_financiero': 'Financial Assistant',
        'hola_asistente': 'Hello, {nombre}. I am your financial assistant.',
        'analisis_asistente': 'I have analyzed your accounts, expenses, and budgets. How can I help you today?',
        'pregunta_placeholder': 'Ask me about your expenses, savings, or budgets...',
        'enviar': 'Send',
        'info_asistente': 'The assistant has access to your monthly balance, top expenses, and current budgets to give you personalized advice.',
        'acciones': 'Actions',
        'divisas': 'Currencies',
        'convertidor_divisas': 'Currency Converter',
        'monto_a_convertir': 'Amount to convert',
        'divisa_origen': 'Source Currency',
        'divisa_destino': 'Target Currency',
        'convertir': 'Convert',
        'resultado_conversion': 'Conversion Result',
        'error_conversion': 'Error obtaining exchange rate.',
    }
}
