[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["echo 'build ok'"]

[start]
cmd = "gunicorn app:app"
